default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: decidim_development

test:
  <<: *default
  database: decidim_test

production:
  <<: *default
  database: decidim_production
